development:
  adapter: mysql2
  database: linkedinscraper
  username: root
  password: root
  host: localhost
  port: 3000
  pool: 40
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

production:
  adapter: mysql2
  database: sql12657348
  username: sql12657348
  password: B6QulrsK2p
  host: sql12.freemysqlhosting.net
  port: 3306
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci