development:
  adapter: mysql2
  database: linkedinscraper
  username: root
  password: root
  host: localhost
  port: 3000
  pool: 40
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

production:
  adapter: mysql2
  database: linkedinscraper_prod_2
  username: root
  password: root
  host: 0.0.0.0
  port: 10000
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  socket: /var/run/mysqld/mysqld.sock